application: renchinmanage
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: static/img
  
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js

- url: /(.*\.html) 
  static_files: static/\1 
  upload: static/(.*)
  
- url: /.*
  script: myapp.app

libraries:
- name: webapp2
  version: latest
